# Generated by Django 4.2.1 on 2023-10-11 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_uploadedimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedimage',
            name='file',
            field=models.FileField(null=True, upload_to='uploads/'),
        ),
    ]
